import joblib
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

train_data = [
    ("falha crítica no servidor", "crítico"),
    ("alerta de segurança detectado", "segurança"),
    ("erro menor no módulo", "aviso"),
    ("backup concluído com sucesso", "informação"),
    ("falha ao conectar banco de dados", "crítico"),
    ("atualização realizada", "informação"),
    ("tentativa de login suspeita", "segurança"),
    ("sistema offline", "crítico"),
    ("perda de dados iminente", "crítico"),
    ("acesso não autorizado", "segurança"),
    ("firewall bloqueado", "segurança"),
    ("desempenho degradado", "aviso"),
    ("disco quase cheio", "aviso"),
    ("novo usuário adicionado", "informação"),
    ("reboot do sistema agendado", "informação"),
    ("processo travado", "crítico"),
    ("arquivo corrompido", "crítico"),
    ("exploração de vulnerabilidade", "segurança"),
    ("vírus detectado", "segurança"),
    ("uso excessivo de memória", "aviso"),
    ("serviço parado", "crítico"),
    ("cópia de segurança falhou", "crítico"),
    ("tentativa de injeção SQL", "segurança"),
    ("portas abertas indevidamente", "segurança"),
    ("configuração alterada", "informação"),
    ("auditoria concluída", "informação"),
    ("licença expirando", "aviso"),
    ("conexão restabelecida", "informação"),
    ("tarefa de manutenção iniciada", "informação"),
    ("timeout da aplicação", "aviso"),
    ("erro de permissão", "aviso"),
    ("autenticação falhou", "segurança"),
    ("dDoS em andamento", "crítico"),
    ("vazamento de dados", "segurança"),
    ("componente superaquecendo", "crítico"),
    ("rede indisponível", "crítico"),
    ("chave SSH comprometida", "segurança"),
    ("novo certificado SSL emitido", "informação"),
    ("log de auditoria limpo", "segurança"),
    ("memória RAM cheia", "crítico"),
    ("sistema reiniciado automaticamente", "crítico"),
    ("exploração de dia zero", "segurança"),
    ("falha na integridade do arquivo", "crítico"),
    ("patch de segurança aplicado", "informação"),
    ("rollback de versão", "aviso"),
    ("disco rígido danificado", "crítico"),
    ("endereço IP bloqueado", "segurança"),
    ("atualização de firmware", "informação"),
    ("interface de rede caiu", "crítico"),
    ("erro de conexão com API", "aviso"),
    ("tentativa de brute force", "segurança"),
    ("serviço DHCP falhou", "crítico"),
    ("recursos esgotados", "crítico"),
    ("análise de segurança agendada", "informação"),
    ("regra de firewall adicionada", "segurança"),
    ("pacotes descartados", "aviso"),
    ("erro de checksum", "aviso"),
    ("restauração de backup", "informação"),
    ("falha no sistema de arquivos", "crítico"),
    ("escalada de privilégios", "segurança"),
    ("conexão VPN caiu", "aviso"),
    ("alta latência de rede", "aviso"),
    ("sistema de logs parado", "crítico"),
    ("dispositivo desconectado", "aviso"),
    ("instalação de software", "informação"),
    ("arquivo deletado", "informação"),
    ("porta USB desabilitada", "segurança"),
    ("alerta de phishing", "segurança"),
    ("tempo de resposta lento", "aviso"),
    ("capacidade do servidor excedida", "crítico"),
    ("erro de roteamento", "aviso"),
    ("novo host detectado", "informação"),
    ("serviço FTP acessado", "informação"),
    ("crescimento inesperado de tráfego", "aviso"),
    ("cache cheio", "aviso"),
    ("acesso negado ao recurso", "segurança"),
    ("servidor de e-mail parado", "crítico"),
    ("falha no processamento de dados", "crítico"),
    ("sessão inválida", "segurança"),
    ("relatório gerado", "informação"),
    ("mudança de senha", "informação"),
    ("processador sobrecarregado", "crítico"),
    ("falha de disco", "crítico"),
    ("falha de autenticação", "segurança"),
    ("conexão com a internet perdida", "crítico"),
    ("novo dispositivo conectado", "informação"),
    ("software desinstalado", "informação"),
    ("temperatura do servidor alta", "aviso"),
    ("erro de configuração de rede", "aviso"),
    ("arquivo movido", "informação"),
    ("perda de pacotes", "aviso"),
    ("vazamento de IP", "segurança"),
    ("falha de energia", "crítico"),
    ("interrupção do serviço", "crítico"),
    ("política de segurança violada", "segurança"),
    ("restauração bem-sucedida", "informação"),
    ("novo backup criado", "informação"),
    ("servidor inacessível", "crítico"),
    ("acesso remoto bloqueado", "segurança"),
    ("download concluído", "informação"),
    ("erro de script", "aviso"),
    ("dados criptografados", "informação"),
    ("anomalia de rede", "segurança"),
]

texts, labels = zip(*train_data)

pipeline = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', MultinomialNB()),
])

pipeline.fit(texts, labels)

joblib.dump(pipeline, 'alert_classifier.joblib')

print("modelo treinado")
